// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLQyCB45axtcWiKYgzwcHL3fTL-gilFw',
    appId: '1:1089749625426:web:e7fb6a8a603c40b6f9cd8b',
    messagingSenderId: '1089749625426',
    projectId: 'talkthrough-7ad4b',
    authDomain: 'talkthrough-7ad4b.firebaseapp.com',
    storageBucket: 'talkthrough-7ad4b.appspot.com',
    measurementId: 'G-PPTZMBY728',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkArEGLfY71QJrCJ6_T6XTbsxCu938u5E',
    appId: '1:1089749625426:android:d7fcb031af27d58af9cd8b',
    messagingSenderId: '1089749625426',
    projectId: 'talkthrough-7ad4b',
    storageBucket: 'talkthrough-7ad4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1C4VyDQBxC0k66UURopcKyJRY3ojkO8w',
    appId: '1:1089749625426:ios:29eaca274f378134f9cd8b',
    messagingSenderId: '1089749625426',
    projectId: 'talkthrough-7ad4b',
    storageBucket: 'talkthrough-7ad4b.appspot.com',
    iosClientId: '1089749625426-i5l6nnmilfoite9psbumdc9co4pb1pre.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkthrough',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1C4VyDQBxC0k66UURopcKyJRY3ojkO8w',
    appId: '1:1089749625426:ios:29eaca274f378134f9cd8b',
    messagingSenderId: '1089749625426',
    projectId: 'talkthrough-7ad4b',
    storageBucket: 'talkthrough-7ad4b.appspot.com',
    iosClientId: '1089749625426-i5l6nnmilfoite9psbumdc9co4pb1pre.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkthrough',
  );
}
